env:
  TERM: xterm-256color
font:
  normal:
    family: FiraCode Nerd Font
    style: Regular
  bold:
    family: FiraCode Nerd Font
    style: Bold
  italic:
    family: FiraCode Nerd Font
    style: Italic
  bold_italic:
    family: FiraCode Nerd Font
    style: Bold Italic
  size: 16
window:
  dynamic_padding: true
  padding:
    x: 10
    y: 10
